### PR TITLE
Add Yarn2 lockfile parser 

### PR DESCRIPTION
**Pull request by Adjective-Object**
Opening this to deal with #36 and https://github.com/microsoft/lage/issues/129

Supports parsing yarn2 lockfiles directly. This change omits a portion of the normalization logic from from [snyk's similar change](https://github.com/snyk/nodejs-lockfile-parser/pull/75/files#diff-b2c66eb5bb9dd1c3dc4998a5d18767af92cc71cd287f5b115a8a602dfc7a275aR27).

When snyk is importing the lockfile, they create every possible representation of a dependency and store duplicate entries for each in their internal representation of a package's lockfile. No other parser in workspace-tools does this at present, so I instead opted for normalizing out the protocol from npm: and file: dependencies (to bring it in line with yarn1 lockfiles), and omitting dependencies where there are incongruities between yarn2's locking and pnpm/yarn1's locking (e.g. workspace dependencies).

### CODE REVIEW

**Comment by Adjective-Object** [comment]
Build is failing because workspace-tools is stuck on typescript @ 3.8 and fails to parse the declaration files in @yarnpkg/core :(

**Comment by AkimaLunar** [comment]
@Adjective-Object, do you need help with the rebase? I just recently added npm 7+ WS support, so this part of the codebase is still pretty fresh in my mind. If you don't have capacity to work on this any more, I could take over.

**Comment by kenotron** [comment]
https://github.com/microsoft/workspace-tools/pull/86 upgrades us to ts4.5. I'll have that done soon. Though I want to caution that if we take on a dep on berry code that:

1. it doesn't get loaded by default - this slows the library down drastically! Please load it with `require()` - I know it's ugly and not ES compliant, but it is currently the only way to ensure your lib is super fast without making the entire API surface async
2. make sure that the @yarnpkg/core code is not conflicting with the @yarnpkg/lockfile that parses yarn v1

**Comment by shaulgo** [comment]
Any idea when this will be merged?

**Comment by Adjective-Object** [comment]
I ended up adopting turbo rather than lage for the personal project that used yarn2, so my I don't need this change merged anymore. If someone else needs it, they're welcome to take this work as a baseline to implement support.

**Pull request closed without merging**
