### PR TITLE
Switch git-status to git-ls-files to detect Untracked files

### LINKED ISSUE #95: git.getUntrackedChanges() is not being parsed correctly
I'm using lage and trying to use the `ignore` field in the configuration.

Anyways, the error I'm seeing is the parser for [`git.getUntrackedChanges()`](https://github.com/microsoft/workspace-tools/blob/master/src/git.ts#L87) is not working as expected.

In my repo, I modify 2 files (that are tracked already) and end up with `[ 'README.md\n M lage.config.js' ]` [here](https://github.com/microsoft/workspace-tools/blob/master/src/git.ts#L114).

Expected: `[]`
Got: `[ 'README.md\n M lage.config.js' ]`

So it ends up causing lage to think every package has changed and it builds everything in the repo when I modify the `README.md` file at the root.

Some details:
```
node: 14.17.4
workspace-tools: 0.18.2
git: 2.35.1
OSX: 12.2.1
```

```sh
daniel.fritz ~/Dev/splat (master !$)
% git status --short
 M README.md
 M lage.config.js

daniel.fritz ~/Dev/splat (master !$)
% git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   README.md
        modified:   lage.config.js

no changes added to commit (use "git add" and/or "git commit -a")

daniel.fritz ~/Dev/splat (master !$)
%
```

### PR DESCRIPTION
**Pull request by dannyfritz**
Fixes #95

### CODE REVIEW

**Comment by dannyfritz** [comment]
bump

**Comment by dannyfritz** [comment]
One more followup to get eyes on this PR. Otherwise I'll have to abandon using lage.

**Review by ecraig12345 — APPROVED** [review]
Thanks!

**Comment by ecraig12345** [comment]
And sorry it took such a long time to get a review.

**Pull request merged**
